### PR TITLE
Implement replay button

### LINKED ISSUE #82: Restartボタンの実装
Forked by https://github.com/unblee/jukebox/issues/64#issuecomment-320492342

### PR DESCRIPTION
**Pull request by sunya9**
Close #82

### CODE REVIEW

**Comment by snakazawa** [comment]
I think `.player-other-controller` needs little padding.

image

What do you think this design?

**Comment by sunya9** [comment]
Surely...

**Comment by unblee** [comment]
When clicking the replay button, noise comes in at the beginning of the audio 🤔

**Comment by unblee** [comment]
I will merge for now.
Thanks! 👍

**Pull request merged**
