### PR TITLE
add travis config

### LINKED ISSUE #68: travis ci 導入

### PR DESCRIPTION
**Pull request by unblee**
close #68

### CODE REVIEW

**Comment by snakazawa** [comment]
I found a hint: https://travis-ci.org/TooTallNate/node-speaker/jobs/199036002#L350

**Comment by snakazawa** [comment]
And https://github.com/TooTallNate/node-speaker/blob/master/package.json#L35

**Comment by sunya9** [comment]
You have to rewrite `.travis.yml`  like the following code.

```yaml
language: node_js

node_js:
  - "8"

addons:
  apt:
    sources:
      - trusty-media
    packages:
      - ffmpeg
      - libasound2-dev

cache: yarn

before_install:
  - yarn config set mpg123-backend dummy

script:
  - yarn run lint:all
  # - yarn run test:all # hasn't test
  - yarn run e2e -- -e chrome-headless
```

In first, `yarn` command is executed before `script` at travis. So, `yarn`  unnecessary to specify explicitly. And, `yarn config` command have to execute in `before_install`.

Furthermore, `yarn run test:all` has not any tests.
This command have to comment out because return exit code 1.

**Comment by snakazawa** [comment]
My Travis CI page for test: https://travis-ci.org/snakazawa/jukebox

**Pull request closed without merging**
