### PR TITLE
Change prev/next buttons behavior to go to prev/next music in one loop mode

### LINKED ISSUE #64: 1ループ再生時に次を押しても次の楽曲にいかない
曲終わりはループが理想だけど、明示的にnextのリクエストを飛ばしたら次の曲へいくのが理想な気がする（前野曲にいくのも同様）。

### PR DESCRIPTION
**Pull request by snakazawa**
This fix #64 .

### CODE REVIEW

**Comment by unblee** [comment]
Umm...
When one loop mode, when the audio ends, the next audio is playing.

**Comment by snakazawa** [comment]
Omg, I will fix that.

**Comment by snakazawa** [comment]
@unblee I fixed the above bug! Please review this again :bow:

**Comment by unblee** [comment]
OK!! 💯 
Thanks!! 👍 👍

**Pull request merged**
