### PR TITLE
Implement "pause"

### PR DESCRIPTION
**Pull request by sunya9**
:tada: :tada: :tada: :tada: :tada: :tada: :tada:

### CODE REVIEW

**Comment by sunya9** [comment]
cf. https://github.com/TooTallNate/node-speaker/issues/52#issuecomment-101366611

**Comment by unblee** [comment]
This is a super great job!!!!!!! 💯 👍 👍 👍 
Thanks for your contribution 👍 👍

**Comment by sunya9** [comment]
まーじまって！！！

**Comment by unblee** [comment]
otto

**Comment by sunya9** [comment]
:ok_woman::ok_woman::ok_woman::ok_woman:

**Comment by unblee** [comment]
OK! 💯 
Thanks! 👍

**Pull request merged**
