### PR TITLE
Use Vuex

### LINKED ISSUE #61: vuexの適用
欲しくなってきた

### PR DESCRIPTION
**Pull request by snakazawa**
close #61 

All data are stored in Vuex store.
All codes for calling API are moved to Vuex actions.
In Vue.component, to clarify the dependencies, `this.$store.*` are not called, instead, `map*` helpers are used (e.g., use `mapActions(...)` instead of `this.$store.dispach(...)`).

### CODE REVIEW

**Comment by snakazawa** [comment]
A part of logs of E2E test in TravisCI is the following:
```
Log type: browser
Log length: 6
  [SEVERE] 1503803170617 : http://localhost:8888/js/clear-playlist-modal.js 17:4 Uncaught SyntaxError: Unexpected token ...
  [SEVERE] 1503803170617 : http://localhost:8888/js/history.js 12:4 Uncaught SyntaxError: Unexpected token ...
  [SEVERE] 1503803170621 : http://localhost:8888/js/playlist.js 8:4 Uncaught SyntaxError: Unexpected token ...
  [SEVERE] 1503803170621 : http://localhost:8888/js/player.js 2:4 Uncaught SyntaxError: Unexpected token ...
  [SEVERE] 1503803170622 : http://localhost:8888/js/links-sender.js 32:4 Uncaught SyntaxError: Unexpected token ...
  [SEVERE] 1503803170622 : http://localhost:8888/js/index.js 14:4 Uncaught SyntaxError: Unexpected token ...
```

For example, `clear-playlist-modal.js` L17-L19 is the following:

```
    },
    ...mapActions(['clearPlaylist'])
  },
```

Object Spread Operator is not supported in Chrome ver 59.
Umm......

**Comment by snakazawa** [comment]
I specified a chrome version by adding `chrome: stable` in `.travis.yml`, but CI was failed (https://docs.travis-ci.com/user/chrome).
Then, I specified to install `google-chrome-stable` from `google-chrome` repository in `.travis.yml`, CI was **succeeded!!** (ttps://github.com/LeaVerou/bliss/issues/117)

**Comment by snakazawa** [comment]
Wait a moment. It is necessary to apply the feature of changing seek to Vuex.

**Comment by snakazawa** [comment]
I fixed conflicts.
@unblee Please review and merge this!

**Comment by unblee** [comment]
LGTM 👍

**Pull request merged**
