### PR TITLE
Force to exit E2E test and refactor

### LINKED ISSUE #94: E2Eテスト終了時に自動的に落ちるようにする
何故か落ちない（多分後ろでapp.jsが動いてるから）。

### PR DESCRIPTION
**Pull request by snakazawa**
## Changes
- Fix to force to exit zombie E2E process ( fixed #94 ).
- Add `E2E_PRESENT_WAIT_TIME` environment (default value is 30,000ms).

## Refactorings
- Change values returned from `src/app.js` from `app` to `{app, server}`.
- Add `server` to values returned from `tests/helper/index.js`.
- Create `e2e/e2e_helper.js`.
- Move common E2E process from each test file to `e2e/globals.js`.
- Divide `e2e/tests/index_test.js` into `e2e/tests/{index, one_loop, playlist_loop}_test.js`.
- Divide each E2E test function into several action functions.
- Remove duplicated clear playlist tests in `e2e/tests/{one_loop, playlist_loop, history}_test.js`.
- Fix typos in E2E test.

## New packages
- `server-destroy`

### CODE REVIEW

**Comment by unblee** [comment]
Please update the environment variable part of the README.

**Comment by unblee** [comment]
I confirmed it works in my environment 👍

**Comment by snakazawa** [comment]
I added the description of E2E tests environments in the configuration section :)

**Comment by unblee** [comment]
OK! 💯 
Thanks!! 👍 👍

**Pull request merged**
