### PR TITLE
Add play history

### PR DESCRIPTION
**Pull request by snakazawa**
This implements play history ( for #52 ).
You can check the behavior of history with E2E test.

Notes:
- I think it is necessary to refactor `*.css` and E2E test, but that should be done after #81 and #89 .
- History item has a unused attribute (`updatedAt`) because I have no idea how to display the attribute well in history view.

### CODE REVIEW

**Comment by snakazawa** [comment]
The appearance of the play history:
image

**Comment by snakazawa** [comment]
- The number displayed on each history item is `playCount`, which is how many times the music was played.
- Last played music is insert or move to top in history view.

**Comment by snakazawa** [comment]
- The number displayed on each history item is `playCount`, which is how many times the music was played.
- Last played music is insert or move to top in history view.

**Comment by unblee** [comment]
screenshot from 2017-08-12 00-15-01
Could you to change the color to `#75b0ba`?

**Comment by snakazawa** [comment]
OK :)

**Comment by snakazawa** [comment]
I fixed tabs color :+1:

Before
image

After
image

**Comment by unblee** [comment]
OK! 💯 
Thanks!! 👍 👍

**Pull request merged**
