### PR TITLE
Remove `ev` and create JukeBox Class

### PR DESCRIPTION
**Pull request by snakazawa**
for #89 

## Important changes:
- Remove EventEmitter instance(`ev`) in `src/app.js`
- Create JukeBox class having `Player`, `PlayerStatus` and `Playlist` instances  in `src/jukebox.js`.
- Provide JukeBox instance on `app.context.jukebox`.
- Reload all status before each E2E test.

### CODE REVIEW

**Comment by unblee** [comment]
Ummm...
After executing the test command, the following log was output.

```
$ yarn run e2e -- -e chrome-headless
yarn run v0.28.4
$ nightwatch --config nightwatch.conf.js "-e" "chrome-headless"
Starting selenium server... started - PID:  8119

[Index Test] Test Suite
===========================

Running:  basicTest
 ✔ Element <body> was visible after 66 milliseconds.
 # log: add musics
 ✖ Timed out while waiting for element <a.playlist-content:nth-child(5)> to be present for 5000 milliseconds.  - expected "found" but got: "not found"
    at Object.basicTest (/home/unblee/workspace/src/github.com/unblee/jukebox/e2e/tests/index_test.js:30:8)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)


FAILED:  1 assertions failed and 1 passed (10.559s)

 _________________________________________________

 TEST FAILURE:  1 assertions failed, 1 passed. (10.94s)

 ✖ index_test

   - basicTest (10.559s)
   Timed out while waiting for element <a.playlist-content:nth-child(5)> to be present for 5000 milliseconds.  - expected "found" but got: "not found"
       at Object.basicTest (/home/unblee/workspace/src/github.com/unblee/jukebox/e2e/tests/index_test.js:30:8)
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
   SKIPPED:
   - oneLoopTest
   - playlistLoopTest
```

**Comment by snakazawa** [comment]
Wait a moment for resolving conflicts.

**Comment by snakazawa** [comment]
OK, I resolved conflicts and checked that E2E test is all green.
Please review this again.

**Comment by unblee** [comment]
Ummm...

```
$ yarn run e2e
...
Running:  oneLoopTest
 ✔ Element <body> was visible after 44 milliseconds.
 # log: add musics
 ✖ Timed out while waiting for element <a.playlist-content:nth-child(5)> to be present for 10000 milliseconds.  - expected "found" but got: "not found"
    at Object.oneLoopTest (/home/unblee/workspace/src/github.com/unblee/jukebox/e2e/tests/index_test.js:105:8)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)


FAILED:  1 assertions failed and 1 passed (15.285s)

 _________________________________________________

 TEST FAILURE:  1 assertions failed, 49 passed. (1m 55s)

 ✖ index_test

   - oneLoopTest (15.285s)
   Timed out while waiting for element <a.playlist-content:nth-child(5)> to be present for 10000 milliseconds.  - expected "found" but got: "not found"
       at Object.oneLoopTest (/home/unblee/workspace/src/github.com/unblee/jukebox/e2e/tests/index_test.js:105:8)
       at _combinedTickCallback (internal/process/next_tick.js:131:7)
       at process._tickCallback (internal/process/next_tick.js:180:9)
   SKIPPED:
   - playlistLoopTest
```

**Comment by snakazawa** [comment]
Is your network speed slow?
Could you try again after set `PRESENT_WAIT_TIME= 30000` in `e2e/tests/index_test.js` and `e2e/tests/history_test.js`.

**Comment by unblee** [comment]
You were right.
I confirmed it works.
Thanks!! 👍 👍

**Pull request merged**
