### PR TITLE
Fix player

### LINKED ISSUE #50: ブラウザの横幅を狭くするとプレビュー画面が消える
image

### LINKED ISSUE #51: 非再生中はプレビューのオーバーレイを表示する
現状だと画面から再生中かどうかが分からない。

### PR DESCRIPTION
**Pull request by sunya9**
Fix #50 
Fix #51

### CODE REVIEW

**Comment by sunya9** [comment]
Resolved conflicts. Review it again.

**Comment by unblee** [comment]
screenshot from 2017-08-11 03-53-43
This is the screenshot when track is zero in playlist.
Is this intentional?

**Comment by sunya9** [comment]
Correctly displayed on my chrome.:thinking::thinking::thinking::thinking:
screenshot from 2017-08-11 04-00-26

**Comment by unblee** [comment]
Umm...
This screenshot was taken with my `firefox`.
Certainly `chrome` will display like your screenshot.

**Comment by snakazawa** [comment]
I suggest killing `firefox` :yum:

**Comment by unblee** [comment]
oh...

**Comment by sunya9** [comment]
I try to change the way to work around. Wait a moment.

**Comment by unblee** [comment]
Thanks 🙏 🙏

**Comment by sunya9** [comment]
Fixed!

**Comment by unblee** [comment]
screenshot from 2017-08-11 04-54-57

**Comment by unblee** [comment]
😫

**Comment by sunya9** [comment]
Fix it :smile:

**Pull request merged**
