### PR TITLE
extract speaker from player

### PR DESCRIPTION
**Pull request by snakazawa**
I extracted Speaker class from Player class for #49.

`src/player.js` was refactored:
- Remove `_playMusic()`.
- Add `get nowPlayingStream()`.
- Use `Speaker.start()` and `Player.nowPlayingStream` instead of `Player._playMusic()` in `start()`. 
- Rename `destroy()` with `stop()`.
- Move register of stream stop event from `_playMusic()` to `constructor()`.

### CODE REVIEW

**Comment by unblee** [comment]
Umm...
If you click the `Next` button, the next audio and the next next audio will be played at the same time.

**Comment by unblee** [comment]
And clicking on any track will play the same audio at the same time.

**Comment by snakazawa** [comment]
Omg... I will check and fix the bugs.

**Comment by unblee** [comment]
😱

**Comment by snakazawa** [comment]
I fixed the bugs :+1:

**Comment by unblee** [comment]
OK! 💯 
This is great work!! 💪 💪 
Thanks!! 👍 👍

**Pull request merged**
