### PR TITLE
Fix speaker delay

### LINKED ISSUE #106: 音量変更時の数秒ディレイを無くす
Streamを理解すれば行けそうな気がする。

### PR DESCRIPTION
**Pull request by snakazawa**
In current master version, operations of stopping music or changing volume is applied to a speaker after 2 or 3 seconds because the speaker has too many buffers.
This PR fix the delay to be less than 1 second with `TimedStream`, `EvenizeStream` (implemented by me in `src/util/evenize_stream.js`) and `PCMVolumeStream` (added in the past PR).

Additionally, This remove `lame.Decoder` and decode with `FFmpeg` instead.

## Known problems
- ~~A little noise may by heard immediately after  #playing music.~~ fixed in 111a609 at 00:20 Aug. 16th.

## Package changes
- Removed `lame`.
- Added `tymed-stream`.

Fixed #106 and #129 .

(edited at 09:32 Aug. 15th.)

### CODE REVIEW

**Comment by unblee** [comment]
Umm...
When the playback button is pressed, the following log is output.

```
error on speaker,  Error: write() failed: 3664
    at onwrite (/home/unblee/workspace/src/github.com/unblee/jukebox/node_modules/speaker/index.js:269:12)
```

**Comment by snakazawa** [comment]
I can't reproduce the bug, but I found another bug and fixed it!

Probably, the bug reported by you is depend in your environment.
Could you re-install `speaker` and check the PR again?
If you change the yarn config of mpg123, fix it before the re-installation.

**Comment by unblee** [comment]
OK. I'll check it.

**Comment by snakazawa** [comment]
Sorry, I fixed kuso typo. Please review this again.

**Comment by unblee** [comment]
The problem is not solved :(

**Comment by snakazawa** [comment]
I confirmed that big using Ubuntu 16.04.
And I found a specification, the write method of node-speaker module expect that **the length of given buffer is a multiple length of `Bit depth / 8 * Channels` only in Linux environment (and Mac?)**.
In this case, it expect a multiple length of **4**, but this PR uses `timed-stream` dividing buffers depend on period time. For example, if the length of the divided buffer is 3666, `node-speaker` throws `write() failed` error.

To deal whith this specification, I implemented `FixMultipleSizeStream` that adjust buffers size to a multiple of a specified number, and added it instead of `EvenizeSteam`..
From this, the reported error no longer exists. I checked this using Windows 10 and Ubuntu 16.04.

Please review this PR again :pray:

**Comment by snakazawa** [comment]
Sorry for including a new bug.
I fixed the bug and added `JUKEBOX_SPEAKER_BUFFER_TIME` environment. The default value is `50`.
This value is the time to send data for internal buffering of speaker before music playback. This value relates to the response time of music stop and volume change, so if this value is large, the response will be delayed. 
I could hear music without noise by setting `50` to the value, but If noise is heard, increase this value (e.g., `JUKEBOX_SPEAKER_BUFFER_TIME=200 yarn start`).

**Comment by snakazawa** [comment]
Well... the bug is not fixed.

**Comment by snakazawa** [comment]
This time, I really truly fixed the bug!

**Comment by unblee** [comment]
OK!! 💯 
This is super super great works!!! ❤️ ❤️ 
Thanks so mutch!!!

**Pull request merged**
