### PR TITLE
Add logo

### LINKED ISSUE #72: ロゴの適用
#11 で使用するロゴを（強行）決定したので WebUI のタイトル部分とかファビコンとかに適用する

### PR DESCRIPTION
**Pull request by sunya9**
Close #72 
Readme's logo will be shown :P

### CODE REVIEW

**Comment by unblee** [comment]
Umm...
Favicon is not displayed.

**Comment by unblee** [comment]
It seems that it is not displayed in firefox.
It is displayed in chrome.

**Comment by snakazawa** [comment]
I was being able to display the favicon in `firefox` by using [koajs/favicon: Koa middleware for serving a favicon](https://github.com/koajs/favicon).

**Comment by snakazawa** [comment]
I added 'chrome-headless' mode.
You can run headless test by `yarn run e2e -- -e chrome-headless`.

I cannot find how to Firefox headless using Nightwatch.

**Comment by sunya9** [comment]
@unblee Fixed! Review again, please. :bow:

**Comment by unblee** [comment]
OK! 💯 
I confirmed that favicon will be displayed in my `firefox` and` chrome`.
Thanks!! 👍 👍

**Pull request merged**
