### PR TITLE
Add dotenv

### LINKED ISSUE #130: .envを入れる

### PR DESCRIPTION
**Pull request by sunya9**
Close #130

### CODE REVIEW

**Comment by snakazawa** [comment]
Can you fill default values in `.env.sample` ?

**Comment by sunya9** [comment]
:ok_woman:

**Comment by sunya9** [comment]
:innocent:

**Comment by sunya9** [comment]
Write to the readme! Please confirm.

**Comment by unblee** [comment]
Thanks!! 👍

**Pull request merged**
